version: '3'

services:
  mongo:
    container_name: openhim-mongo
    ports:
      - "27017:27017"
    image: mongo:4.0
    
  core:
    container_name: openhim-core
    image: jembi/openhim-core
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
      - openhimConsoleBaseUrl=http://raspberrypi.tail126a09.ts.net:9000
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
  
  console:
    container_name: openhim-console
    image: jembi/openhim-console
    ports:
        - "9000:80"
    # entrypoint: |
    #   sh -c '
    #   mkdir -p /usr/share/nginx/html/config &&
    #   cat > /usr/share/nginx/html/config/default.json <<EOF
    #   {
    #     "version": "1.10.0",
    #     "minimumCoreVersion": "3.4.0",
    #     "protocol": "https",
    #     "host": "raspberrypi",
    #     "port": 8080,
    #     "title": "Admin Console",
    #     "footerTitle": "OpenHIM Administration Console",
    #     "footerPoweredBy": "<a href=\"http://openhim.org/\" target=\"_blank\">Powered by OpenHIM</a>",
    #     "loginBanner": "",
    #     "mediatorLastHeartbeatWarningSeconds": 60,
    #     "mediatorLastHeartbeatDangerSeconds": 120
    #   }
    #   EOF
    #   exec nginx -g "daemon off;" // consider removing this if you face issues
    #   '
    entrypoint: |
      sh -c '
      mkdir -p /usr/share/nginx/html/config &&
      cat > /usr/share/nginx/html/config/default.json <<EOF
      {
        "version": "1.18.2",
        "minimumCoreVersion": "5.2.0",
        "protocol": "https",
        "host": "raspberrypi",
        "hostPath": "",
        "port": "8080",
        "title": "Admin Console",
        "footerTitle": "OpenHIM Administration Console",
        "footerPoweredBy": "<a href=\"http://openhim.org/\" target=\"_blank\">Powered by OpenHIM</a>",
        "loginBanner": "",
        "mediatorLastHeartbeatWarningSeconds": 60,
        "mediatorLastHeartbeatDangerSeconds": 120,
        "showLoginForm": true,
        "ssoEnabled": false,
        "keyCloakUrl": "http://localhost:9088",
        "keyCloakRealm": "platform-realm",
        "keyCloakClientId": "openhim-oauth"
      }
      EOF'
